# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Escuela de Incidencia
email: hola@escueladeincidencia.org
description: La Escuela de Incidencia es una iniciativa de Ciudadano Inteligente, realizada con el apoyo de National Endowment for Democracy, que busca fomentar el liderazgo colaborativo y participativo de nuevas generaciones para lograr cambios sociales a través de procesos de incidencia en el ámbito gubernamental
baseurl: '//escueladeincidencia.org' #"//ciudadanointeligente/escueladeincidencia.github.io"
basedomain: escueladeincidencia.org
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-76464035-3'

# Build settings
markdown: kramdown
