# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Escuela de Incidencia
email: hola@escueladeincidencia.org
description: Entregamos herramientas para cambiar el mundo. Conoce La Escuela de Incidencia de Ciudadano Inteligente
keywords: incidencia, sociedad civil, capacitación, organización, activismo, liderazgo, jóvenes, latinoamérica, democracia, medioambiente, diversidad sexual, género, transparencia
baseurl: '//escueladeincidencia.org' #"//ciudadanointeligente/escueladeincidencia.github.io"
basedomain: escueladeincidencia.org
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
analytics: 'UA-76464035-3'

# Build settings
markdown: kramdown

pluguins: ['shuffle']

collections:
  repocards:
    output: true
